name: Build and Deploy Docker (Frontend & Backend)

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/krph_frontend ./frontend

      - name: Push Frontend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/krph_frontend

      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/krph_backend ./backend

      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/krph_backend

  deploy:
    name: Deploy to VPS using docker-compose
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy using docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/KRPhotography
            docker-compose stop
            docker rmi -f dimpex/krph_backend
            docker rmi -f dimpex/krph_frontend
            docker-compose up -d
            docker-compose exec backend python manage.py migrate
            docker-compose exec backend python manage.py collectstatic --noinput
